# Generated by Django 4.0 on 2022-01-14 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211124_1202'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wishlist',
            new_name='Favourites',
        ),
    ]
