# Generated by Django 4.0 on 2021-12-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='nutrition',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='plans',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='price',
            field=models.DecimalField(
                decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='price',
            field=models.DecimalField(
                decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='plans',
            name='price',
            field=models.DecimalField(
                decimal_places=2, max_digits=6, null=True),
        ),
    ]
