# Generated by Django 4.0 on 2021-12-30 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_exercise_friendly_name_nutrition_friendly_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plans',
            new_name='Plan',
        ),
    ]
