# Generated by Django 4.0 on 2021-12-30 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_rename_plans_plan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
