# Generated by Django 4.0 on 2022-01-01 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_rename_plans_plan'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plan',
            new_name='Plans',
        ),
    ]
