# Generated by Django 4.0 on 2022-01-02 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0008_rename_plans_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='category',
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='category',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.DeleteModel(
            name='Nutrition',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
