# Generated by Django 4.0 on 2022-01-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_options_rename_user_post_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Title', max_length=255),
        ),
    ]
