# Generated by Django 4.0 on 2022-01-07 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_hub', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='FitnessHub',
        ),
    ]
