# Generated by Django 4.0 on 2022-01-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_hub', '0002_rename_post_fitnesshub'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnesshub',
            name='fitness_hub_fitnesshub',
            field=models.TextField(max_length=140, null=True),
        ),
    ]
