# Generated by Django 4.0 on 2022-01-08 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_hub', '0003_fitnesshub_fitness_hub_fitnesshub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnesshub',
            name='text',
        ),
    ]
