# Generated by Django 4.0 on 2022-01-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_hub', '0004_remove_fitnesshub_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnesshub',
            name='text',
            field=models.TextField(max_length=140, null=True),
        ),
    ]
