# Generated by Django 4.0 on 2022-01-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_hub', '0005_fitnesshub_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnesshub',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
