# Generated by Django 4.0 on 2022-01-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_hub', '0007_fitnesshub_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnesshub',
            name='name',
            field=models.CharField(blank=True, default=False, max_length=254, null=True),
        ),
    ]
