# Generated by Django 4.0 on 2022-01-08 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_hub', '0008_alter_fitnesshub_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnesshub',
            name='fitness_hub_fitnesshub',
        ),
    ]
