# Generated by Django 4.0 on 2022-01-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_hub', '0009_remove_fitnesshub_fitness_hub_fitnesshub'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnesshub',
            name='message',
            field=models.TextField(default=False),
        ),
    ]
