# Generated by Django 5.2.4 on 2025-07-25 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=254, verbose_name="Name")),
                (
                    "friendly_name",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=254)),
                ("description", models.TextField(verbose_name="Description")),
                ("gender", models.TextField(null=True, verbose_name="Gender")),
                ("colour", models.TextField(null=True, verbose_name="Colour")),
                (
                    "has_sizes",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True, max_length=1024, null=True, verbose_name="Image url"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="Image"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.category",
                    ),
                ),
            ],
        ),
    ]
