# Generated by Django 4.1.7 on 2023-03-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.TextField(null=True, verbose_name='Gender'),
        ),
    ]
