# Generated by Django 3.2 on 2023-06-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colour',
            field=models.TextField(null=True, verbose_name='Colour'),
        ),
    ]
